version: '3.7'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: unless-stopped
    user: 1000:1000
    ports:
      - 8096:8096
    labels:
      - 'traefik.enable=true'
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
      - "traefik.http.routers.jellyfin.tls=true"
      - "traefik.http.routers.jellyfin.rule=Host(`${JELLYFIN_DOMAIN}`)"
      - "traefik.http.routers.jellyfin.entrypoints=https"
      - "traefik.http.routers.jellyfin.tls.certresolver=letsencrypt"
      - "traefik.http.middlewares.jellfin.redirectscheme.scheme=https"
      - "traefik.http.middlewares.jellyfin.redirectscheme.permanent=true"
      - "traefik.http.routers.jellyfin.middlewares=jellfin"
    volumes:
      - ./data/config:/config
      - ./data/cache:/cache
      - ./data/media:/media 
    devices:
      - /dev/dri:/dev/dri
    networks:
      - proxy

networks:
  proxy:
    external:
      name: proxy
